### PR TITLE
Release 1.4.0 for 2.3.x

### PR DESCRIPTION
**Pull request by TomAbel**
# Plugin Version : 1.4.0

**Version changelog**

A list of changes regarding the next version release:

1. More user-friendly RSS URL generation with extra parameters - #96 
2. Unify use of first_name and last_name field names - #98
3. Add language field to form - #103 

**Release checklist**

- [X] Added `release` and appropriate platform version tag to this pull request
- [X] Updated README.md
- [X] Updated CHANGELOG.md
- [X] Updated plugin version number
- [X] Updated screenshots in assets folder
- [X] Updated translations

**After PR merge**

- [ ] Released new version in GitHub
- [ ] Updated plugin on the OpenCart marketplace
- [ ] Pinged code owners to inform marketing about new version

### CODE REVIEW

**Review by kaittodesk — APPROVED** [review]

**Comment by kaittodesk** [comment]
Wait, you haven't updated the CHANGELOG.md.

**Review by kaittodesk — CHANGES_REQUESTED** [review]
Missing changes in the CHANGELOG.md

**Comment by TomAbel** [comment]
> Missing changes in the CHANGELOG.md

this should be in commit [1ac8825](https://github.com/sendsmaily/smaily-opencart-module/pull/116/commits/1ac8825d5685c7e97358767836bb5e90cb97602c)

**Review by kaittodesk — APPROVED** [review]
Odd, I only saw 7 changed files and no updates in README or CHANGELOG.

**Pull request merged**
